import {useRef} from 'react';
import type React from 'react';
import {clamp,fmt,type Clip,type Plate,type Position,type ProjectLogo,type Slot,type SponsorType,type Transform} from './model';

export function Video({clip,t,onT,active}:{clip:Clip;t:Transform;onT:(t:Transform)=>void;active:boolean}){const host=useRef<HTMLDivElement>(null),pts=useRef(new Map<number,{x:number;y:number}>()),start=useRef<any>(null),pinch=useRef<any>(null);const down=(e:React.PointerEvent<HTMLDivElement>)=>{if(!active)return;e.currentTarget.setPointerCapture(e.pointerId);pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.current.size===1)start.current={x:e.clientX,y:e.clientY,t:{...t}};if(pts.current.size===2){const[a,b]=[...pts.current.values()];pinch.current={d:Math.hypot(a.x-b.x,a.y-b.y),z:t.zoom}}};const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(!active||!pts.current.has(e.pointerId))return;pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.current.size===2&&pinch.current){const[a,b]=[...pts.current.values()];onT({...t,zoom:clamp(pinch.current.z*Math.hypot(a.x-b.x,a.y-b.y)/pinch.current.d,.55,4)});return}if(start.current&&host.current){const r=host.current.getBoundingClientRect();onT({...start.current.t,panX:clamp(start.current.t.panX+(e.clientX-start.current.x)/r.width*1.4,-1,1),panY:clamp(start.current.t.panY+(e.clientY-start.current.y)/r.height*1.4,-1,1)})}};const up=(e:React.PointerEvent<HTMLDivElement>)=>{pts.current.delete(e.pointerId);start.current=null;pinch.current=null};return <div ref={host} className="v3video" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{clip.url?<video src={clip.url} muted loop autoPlay playsInline style={{transform:`translate(${t.panX*28}%,${t.panY*28}%) scale(${t.zoom})`}}/>:<div className="v3empty">ДОБАВЬ ВИДЕО</div>}{active&&<i/>}</div>}

export function Drag({stage,pos,onPos,children,cls=''}:{stage:React.RefObject<HTMLDivElement|null>;pos:Position;onPos:(p:Position)=>void;children:React.ReactNode;cls?:string}){const s=useRef<any>(null);const d=(e:React.PointerEvent<HTMLDivElement>)=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);s.current={px:e.clientX,py:e.clientY,...pos}};const m=(e:React.PointerEvent<HTMLDivElement>)=>{if(!s.current||!stage.current)return;const r=stage.current.getBoundingClientRect();onPos({x:clamp(s.current.x+(e.clientX-s.current.px)/r.width,0,.95),y:clamp(s.current.y+(e.clientY-s.current.py)/r.height,0,.95)})};return <div className={'v3drag '+cls} style={{left:`${pos.x*100}%`,top:`${pos.y*100}%`}} onPointerDown={d} onPointerMove={m} onPointerUp={()=>s.current=null} onPointerCancel={()=>s.current=null}>{children}</div>}

function Words({p}:{p:Plate}){let wi=0;return <>{p.text.toUpperCase().split(/(\s+)/).map((x,i)=>{if(/^\s+$/.test(x)){const n=(x.match(/\n/g)||[]).length;return n?<span key={i}>{Array.from({length:n},(_,j)=><br key={j}/>)}</span>:<span key={i}> </span>}const k=wi++;return <span key={i} style={{color:p.wordColors[k]||p.textColor}}>{x}</span>})}</>}
export const PlateBox=({p}:{p:Plate})=><div className="v3plate" style={{background:p.backgroundColor,borderColor:p.borderEnabled?p.borderColor:'transparent',borderRadius:p.radius/3,maxWidth:`${p.maxWidth/1080*100}vw`,padding:`${p.paddingY/3}px ${p.paddingX/3}px`,fontSize:p.fontSize/3,lineHeight:`calc(1em + ${p.lineGap/3}px)`,textAlign:p.align}}><Words p={p}/></div>;
export const ProjectLogoImg=({scale=1}:{scale?:number})=><img className="v3projectLogo" src="/brand/ves-sport.svg" style={{transform:`scale(${scale})`}}/>;
export const Sponsor=({type}:{type:Exclude<SponsorType,'none'>})=><img className={'v3sponsor '+type} src={type==='winline'?'/brand/winline.png':'/brand/difference.png'}/>;

export function FileRow({slot,clip,setFile}:{slot:Slot;clip:Clip;setFile:(s:Slot,f?:File)=>void}){const r=useRef<HTMLInputElement>(null);return <button className="v3file" onClick={()=>r.current?.click()}><input ref={r} hidden type="file" accept="video/*" onChange={e=>setFile(slot,e.target.files?.[0])}/><b>{slot}</b><span>{clip.file?.name||'Выбрать видео'}</span><em>ЗАМЕНИТЬ</em></button>}
export function Trim({clip,setClip}:{clip:Clip;setClip:React.Dispatch<React.SetStateAction<Clip>>}){const max=Math.max(.05,clip.duration);const setIn=(x:number)=>setClip(v=>({...v,trimStart:clamp(x,0,Math.max(0,v.trimEnd-.05))}));const setOut=(x:number)=>setClip(v=>({...v,trimEnd:clamp(x,Math.min(v.duration,v.trimStart+.05),v.duration)}));return <div className="v3trim"><div className="v3trimHead"><b>ОБРЕЗКА</b><span>{fmt(clip.trimStart)} → {fmt(clip.trimEnd)} · итог {fmt(clip.trimEnd-clip.trimStart)} сек</span></div><label>НАЧАЛО <input type="range" min={0} max={max} step="0.05" value={clip.trimStart} onChange={e=>setIn(Number(e.target.value))}/><input type="number" min={0} max={clip.trimEnd-.05} step="0.05" value={clip.trimStart} onChange={e=>setIn(Number(e.target.value))}/></label><label>КОНЕЦ <input type="range" min={0} max={max} step="0.05" value={clip.trimEnd} onChange={e=>setOut(Number(e.target.value))}/><input type="number" min={clip.trimStart+.05} max={clip.duration} step="0.05" value={clip.trimEnd} onChange={e=>setOut(Number(e.target.value))}/></label></div>}
export function Range({label,value,min,max,set}:{label:string;value:number;min:number;max:number;set:(n:number)=>void}){return <label className="v3range"><span>{label}<b>{value}</b></span><input type="range" value={value} min={min} max={max} onChange={e=>set(Number(e.target.value))}/></label>}
export function Color({label,value,set}:{label:string;value:string;set:(s:string)=>void}){return <label className="v3color">{label}<input type="color" value={value} onChange={e=>set(e.target.value)}/></label>}
