import { useEffect, useMemo, useRef, useState } from 'react';

type Layout='single'|'split-full'; type Slot='A'|'B'; type Transform={zoom:number;panX:number;panY:number}; type Position={x:number;y:number};
type Clip={file:File|null;url:string;key:string;duration:number;trimStart:number;trimEnd:number;single:Transform;split:Transform;full:Transform};
type SponsorType='none'|'winline'|'difference'; type Output='clean'|'plate'|'sponsor'|'combined';
type Plate={enabled:boolean;text:string;position:Position;backgroundColor:string;borderColor:string;borderEnabled:boolean;textColor:string;wordColors:Record<number,string>;fontSize:number;maxWidth:number;radius:number;paddingX:number;paddingY:number;lineGap:number;align:'left'|'center'|'right'};
type ProjectLogo={enabled:boolean;mode:'linked'|'free';position:Position;scale:number;gap:number};
const T={zoom:1,panX:0,panY:0}; const blank=():Clip=>({file:null,url:'',key:'',duration:0,trimStart:0,trimEnd:0,single:{...T},split:{...T},full:{...T}});
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v)); const uid=()=>crypto.randomUUID();
const sponsorDefaults={winline:{x:740/1080,y:336/1920},difference:{x:626/1080,y:336/1920}};
async function duration(file:File){return await new Promise<number>((res,rej)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{const d=v.duration;URL.revokeObjectURL(u);res(Number.isFinite(d)?d:0)};v.onerror=()=>rej(new Error('Не удалось прочитать видео'));v.src=u})}
async function upload(file:File,key:string,progress:(n:number)=>void){const c=await fetch('/api/upload/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key,contentType:file.type||'video/mp4'})});if(!c.ok)throw new Error(await c.text());const {uploadId}=await c.json();const size=8*1024*1024,count=Math.ceil(file.size/size),parts=[];for(let i=0;i<count;i++){const r=await fetch(`/api/upload/part?key=${encodeURIComponent(key)}&uploadId=${encodeURIComponent(uploadId)}&partNumber=${i+1}`,{method:'PUT',body:file.slice(i*size,Math.min((i+1)*size,file.size))});if(!r.ok)throw new Error(await r.text());parts.push(await r.json());progress((i+1)/count)}const x=await fetch('/api/upload/complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key,uploadId,parts})});if(!x.ok)throw new Error(await x.text())}
function Video({clip,t,onT,active}:{clip:Clip;t:Transform;onT:(t:Transform)=>void;active:boolean}){const host=useRef<HTMLDivElement>(null),pts=useRef(new Map<number,{x:number;y:number}>()),start=useRef<any>(null),pinch=useRef<any>(null);const down=(e:React.PointerEvent<HTMLDivElement>)=>{if(!active)return;e.currentTarget.setPointerCapture(e.pointerId);pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.current.size===1)start.current={x:e.clientX,y:e.clientY,t:{...t}};if(pts.current.size===2){const[a,b]=[...pts.current.values()];pinch.current={d:Math.hypot(a.x-b.x,a.y-b.y),z:t.zoom}}};const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(!active||!pts.current.has(e.pointerId))return;pts.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.current.size===2&&pinch.current){const[a,b]=[...pts.current.values()];onT({...t,zoom:clamp(pinch.current.z*Math.hypot(a.x-b.x,a.y-b.y)/pinch.current.d,1,4)});return}if(start.current&&host.current){const r=host.current.getBoundingClientRect();onT({...start.current.t,panX:clamp(start.current.t.panX-(e.clientX-start.current.x)/r.width*1.5,-1,1),panY:clamp(start.current.t.panY-(e.clientY-start.current.y)/r.height*1.5,-1,1)})}};const up=(e:React.PointerEvent<HTMLDivElement>)=>{pts.current.delete(e.pointerId);start.current=null;pinch.current=null};return <div ref={host} className="v2video" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{clip.url?<video src={clip.url} muted loop autoPlay playsInline style={{transform:`translate(${-t.panX*18}%,${-t.panY*18}%) scale(${t.zoom})`}}/>:<div className="v2empty">ДОБАВЬ ВИДЕО</div>}{active&&<i/>}</div>}
function Drag({stage,pos,onPos,children,cls=''}:{stage:React.RefObject<HTMLDivElement|null>;pos:Position;onPos:(p:Position)=>void;children:React.ReactNode;cls?:string}){const s=useRef<any>(null);const d=(e:React.PointerEvent<HTMLDivElement>)=>{e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);s.current={px:e.clientX,py:e.clientY,...pos}};const m=(e:React.PointerEvent<HTMLDivElement>)=>{if(!s.current||!stage.current)return;const r=stage.current.getBoundingClientRect();onPos({x:clamp(s.current.x+(e.clientX-s.current.px)/r.width,0,.95),y:clamp(s.current.y+(e.clientY-s.current.py)/r.height,0,.95)})};return <div className={'v2drag '+cls} style={{left:`${pos.x*100}%`,top:`${pos.y*100}%`}} onPointerDown={d} onPointerMove={m} onPointerUp={()=>s.current=null} onPointerCancel={()=>s.current=null}>{children}</div>}
function Words({p}:{p:Plate}){let wi=0;return <>{p.text.toUpperCase().split(/(\s+)/).map((x,i)=>{if(/^\s+$/.test(x)){const n=(x.match(/\n/g)||[]).length;return n?<span key={i}>{Array.from({length:n},(_,j)=><br key={j}/>)}</span>:<span key={i}> </span>}const k=wi++;return <span key={i} style={{color:p.wordColors[k]||p.textColor}}>{x}</span>})}</>}
const PlateBox=({p}:{p:Plate})=><div className="v2plate" style={{background:p.backgroundColor,borderColor:p.borderEnabled?p.borderColor:'transparent',borderRadius:p.radius/3,maxWidth:`${p.maxWidth/1080*100}vw`,padding:`${p.paddingY/3}px ${p.paddingX/3}px`,fontSize:p.fontSize/3,lineHeight:`calc(1em + ${p.lineGap/3}px)`,textAlign:p.align}}><Words p={p}/></div>;
const ProjectLogoImg=({scale=1}:{scale?:number})=><img className="v2projectLogo" src="/brand/ves-sport.png" style={{transform:`scale(${scale})`}}/>;
const Sponsor=({type}:{type:Exclude<SponsorType,'none'>})=><img className={'v2sponsor '+type} src={type==='winline'?'/brand/winline.png':'/brand/difference.png'}/>;
export default function AppV2(){const stage=useRef<HTMLDivElement>(null);const[layout,setLayout]=useState<Layout>('single'),[a,setA]=useState<Clip>(blank),[b,setB]=useState<Clip>(blank),[slot,setSlot]=useState<Slot>('A'),[preview,setPreview]=useState<'split'|'full'>('split');const[plate,setPlate]=useState<Plate>({enabled:true,text:'МЕНДЕШ ОТКАЗАЛСЯ ЖАТЬ РУКУ НЕЙМАРУ',position:{x:.08,y:.10},backgroundColor:'#111111',borderColor:'#ff5b11',borderEnabled:true,textColor:'#ffffff',wordColors:{},fontSize:52,maxWidth:860,radius:18,paddingX:24,paddingY:12,lineGap:4,align:'left'});const[sponsor,setSponsor]=useState<{type:SponsorType;position:Position;scale:number}>({type:'winline',position:sponsorDefaults.winline,scale:1});const[project,setProject]=useState<ProjectLogo>({enabled:false,mode:'linked',position:{x:.03,y:.1},scale:1,gap:16});const[outputs,setOutputs]=useState<Output[]>(['combined']),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[job,setJob]=useState(''),[status,setStatus]=useState(''),[files,setFiles]=useState<any[]>([]),[error,setError]=useState('');const words=useMemo(()=>plate.text.trim().split(/\s+/).filter(Boolean),[plate.text]);
const setFile=async(s:Slot,f?:File)=>{if(!f)return;try{const d=await duration(f),n={...blank(),file:f,url:URL.createObjectURL(f),duration:d,trimEnd:d};s==='A'?setA(n):setB(n)}catch(e){setError(String(e))}};
const active=layout==='single'?a.single:slot==='A'?a.split:preview==='split'?b.split:b.full;const setActive=(t:Transform)=>layout==='single'?setA(v=>({...v,single:t})):slot==='A'?setA(v=>({...v,split:t})):preview==='split'?setB(v=>({...v,split:t})):setB(v=>({...v,full:t}));
const up=async(c:Clip,w0:number,w:number)=>{if(!c.file||c.key)return c;const key=`uploads/${uid()}-${c.file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await upload(c.file,key,p=>setProgress((w0+p*w)*100));return {...c,key}};
const render=async()=>{if(!a.file||(layout==='split-full'&&!b.file)||!outputs.length)return;setBusy(true);setError('');setFiles([]);try{const count=layout==='single'?1:2,aa=await up(a,0,1/count),bb=layout==='split-full'?await up(b,1/count,1/count):b;setA(aa);if(layout==='split-full')setB(bb);const r=await fetch('/api/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({layout,videoA:{key:aa.key,sourceDuration:aa.duration,trimStart:aa.trimStart,trimEnd:aa.trimEnd,single:aa.single,split:aa.split},videoB:layout==='split-full'?{key:bb.key,sourceDuration:bb.duration,trimStart:bb.trimStart,trimEnd:bb.trimEnd,split:bb.split,full:bb.full}:null,audioMode:'b',plate:{...plate,text:plate.text.toUpperCase(),x:plate.position.x,y:plate.position.y},sponsor:{...sponsor,x:sponsor.position.x,y:sponsor.position.y},projectLogo:{...project,x:project.position.x,y:project.position.y},outputs})});if(!r.ok)throw new Error(await r.text());const j=await r.json();setJob(j.jobId);setStatus('queued')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
useEffect(()=>{if(!job)return;let stop=false;const poll=async()=>{try{const r=await fetch(`/api/jobs/${job}`);if(!r.ok||stop)return;const j=await r.json();setStatus(j.status);if(j.status==='done')return setFiles(j.outputs||[]);if(j.status==='failed')return setError(j.error||'Ошибка рендера');setTimeout(poll,2000)}catch{if(!stop)setTimeout(poll,3000)}};poll();return()=>{stop=true}},[job]);
const toggle=(o:Output)=>setOutputs(v=>v.includes(o)?v.filter(x=>x!==o):[...v,o]);
return <main className="v2main"><header><b>ZNAMBO VIDEO RENDERER</b><span>1080×1920</span></header><div className="v2seg"><button className={layout==='single'?'on':''} onClick={()=>setLayout('single')}>ОДНО ВИДЕО</button><button className={layout==='split-full'?'on':''} onClick={()=>setLayout('split-full')}>ДВА → FULL</button></div>
<div className="v2stageWrap"><div ref={stage} className="v2stage">{layout==='single'?<Video clip={a} t={a.single} active onT={t=>setA(v=>({...v,single:t}))}/>:preview==='full'?<Video clip={b} t={b.full} active onT={t=>setB(v=>({...v,full:t}))}/>:<><div className="v2half top" onClick={()=>setSlot('A')}><Video clip={a} t={a.split} active={slot==='A'} onT={t=>setA(v=>({...v,split:t}))}/></div><div className="v2half bottom" onClick={()=>setSlot('B')}><Video clip={b} t={b.split} active={slot==='B'} onT={t=>setB(v=>({...v,split:t}))}/></div></>}
{plate.enabled&&plate.text.trim()&&(project.enabled&&project.mode==='linked'?<Drag stage={stage} pos={plate.position} onPos={p=>setPlate(v=>({...v,position:p}))} cls="v2linked"><div className="v2linkedRow" style={{gap:project.gap/3}}><ProjectLogoImg scale={project.scale}/><PlateBox p={plate}/></div></Drag>:<Drag stage={stage} pos={plate.position} onPos={p=>setPlate(v=>({...v,position:p}))}><PlateBox p={plate}/></Drag>)}
{project.enabled&&project.mode==='free'&&<Drag stage={stage} pos={project.position} onPos={p=>setProject(v=>({...v,position:p}))}><ProjectLogoImg scale={project.scale}/></Drag>}
{sponsor.type!=='none'&&<Drag stage={stage} pos={sponsor.position} onPos={p=>setSponsor(v=>({...v,position:p}))}><div style={{transform:`scale(${sponsor.scale})`,transformOrigin:'top left'}}><Sponsor type={sponsor.type}/></div></Drag>}</div><small>Видео, плашку и логотипы можно двигать пальцем</small></div>
{layout==='split-full'&&<section><h2>ПРЕВЬЮ B</h2><div className="v2seg"><button className={preview==='split'?'on':''} onClick={()=>setPreview('split')}>SPLIT</button><button className={preview==='full'?'on':''} onClick={()=>{setPreview('full');setSlot('B')}}>B FULL</button></div></section>}
<section><h2>КАДР</h2><div className="v2grid4"><button onClick={()=>setActive({...active,zoom:clamp(active.zoom-.1,1,4)})}>− ЗУМ</button><button onClick={()=>setActive({...active,zoom:clamp(active.zoom+.1,1,4)})}>+ ЗУМ</button><button onClick={()=>setActive({...active,panX:0,panY:0})}>ЦЕНТР</button><button onClick={()=>setActive({...T})}>RESET</button></div></section>
<section><h2>ВИДЕО</h2><File slot="A" clip={a} setFile={setFile}/>{layout==='split-full'&&<File slot="B" clip={b} setFile={setFile}/>}</section>
<section><h2>ТЕКСТОВАЯ ПЛАШКА</h2><label className="v2switch"><input type="checkbox" checked={plate.enabled} onChange={e=>setPlate(v=>({...v,enabled:e.target.checked}))}/> ВКЛ</label><textarea rows={3} value={plate.text} onChange={e=>setPlate(v=>({...v,text:e.target.value,wordColors:{}}))}/><div className="v2row"><Color label="ФОН" value={plate.backgroundColor} set={x=>setPlate(v=>({...v,backgroundColor:x}))}/><Color label="ТЕКСТ" value={plate.textColor} set={x=>setPlate(v=>({...v,textColor:x}))}/><Color label="ОБВОДКА" value={plate.borderColor} set={x=>setPlate(v=>({...v,borderColor:x}))}/></div><div className="v2seg"><button className={plate.align==='left'?'on':''} onClick={()=>setPlate(v=>({...v,align:'left'}))}>СЛЕВА</button><button className={plate.align==='center'?'on':''} onClick={()=>setPlate(v=>({...v,align:'center'}))}>ЦЕНТР</button><button className={plate.align==='right'?'on':''} onClick={()=>setPlate(v=>({...v,align:'right'}))}>СПРАВА</button></div><Range label="Ширина строки / плашки" value={plate.maxWidth} min={260} max={1000} set={x=>setPlate(v=>({...v,maxWidth:x}))}/><Range label="Отступ по бокам" value={plate.paddingX} min={0} max={120} set={x=>setPlate(v=>({...v,paddingX:x}))}/><Range label="Отступ сверху/снизу" value={plate.paddingY} min={0} max={80} set={x=>setPlate(v=>({...v,paddingY:x}))}/><Range label="Межстрочный интервал" value={plate.lineGap} min={-10} max={40} set={x=>setPlate(v=>({...v,lineGap:x}))}/><Range label="Размер текста" value={plate.fontSize} min={28} max={110} set={x=>setPlate(v=>({...v,fontSize:x}))}/><div className="v2words">{words.map((w,i)=><label key={i}>{w.toUpperCase()}<input type="color" value={plate.wordColors[i]||plate.textColor} onChange={e=>setPlate(v=>({...v,wordColors:{...v.wordColors,[i]:e.target.value}}))}/></label>)}</div></section>
<section><h2>ЛОГО «ВЕСЬ СПОРТ»</h2><label className="v2switch"><input type="checkbox" checked={project.enabled} onChange={e=>setProject(v=>({...v,enabled:e.target.checked}))}/> ВКЛ</label>{project.enabled&&<><div className="v2seg"><button className={project.mode==='linked'?'on':''} onClick={()=>setProject(v=>({...v,mode:'linked'}))}>СЛЕВА ОТ ПЛАШКИ</button><button className={project.mode==='free'?'on':''} onClick={()=>setProject(v=>({...v,mode:'free'}))}>СВОБОДНО</button></div><Range label="Размер" value={Math.round(project.scale*100)} min={40} max={200} set={x=>setProject(v=>({...v,scale:x/100}))}/>{project.mode==='linked'&&<Range label="Отступ до плашки" value={project.gap} min={0} max={120} set={x=>setProject(v=>({...v,gap:x}))}/>}<div className="v2hint">В режиме привязки логотип всегда центрируется по высоте плашки и двигается вместе с ней.</div></>}</section>
<section><h2>ЛОГО WINLINE</h2><div className="v2seg"><button className={sponsor.type==='none'?'on':''} onClick={()=>setSponsor(v=>({...v,type:'none'}))}>НЕТ</button><button className={sponsor.type==='winline'?'on':''} onClick={()=>setSponsor({type:'winline',position:sponsorDefaults.winline,scale:1})}>WINLINE</button><button className={sponsor.type==='difference'?'on':''} onClick={()=>setSponsor({type:'difference',position:sponsorDefaults.difference,scale:1})}>ДЕЛАЕТ РАЗНИЦУ</button></div></section>
<section><h2>ВЕРСИИ НА ВЫХОДЕ</h2>{(['clean','plate','sponsor','combined'] as Output[]).map(o=><button key={o} className={'v2out '+(outputs.includes(o)?'on':'')} onClick={()=>toggle(o)}>{outputs.includes(o)?'✓ ':''}{o==='clean'?'Чистая':o==='plate'?'Только плашка':o==='sponsor'?'Только лого': 'Плашка + лого'}</button>)}</section>{error&&<div className="v2error">{error}</div>}{job&&<section><h2>РЕНДЕР: {status}</h2>{files.map(f=><a key={f.key} href={`/api/files/${encodeURIComponent(f.key)}`}>{f.preset.toUpperCase()}.MP4</a>)}</section>}<button className="v2render" disabled={busy||!a.file||(layout==='split-full'&&!b.file)} onClick={render}>{busy?`ЗАГРУЗКА ${Math.round(progress)}%`:`РЕНДЕР ${outputs.length}`}</button></main>}
function File({slot,clip,setFile}:{slot:Slot;clip:Clip;setFile:(s:Slot,f?:File)=>void}){const r=useRef<HTMLInputElement>(null);return <button className="v2file" onClick={()=>r.current?.click()}><input ref={r} hidden type="file" accept="video/*" onChange={e=>setFile(slot,e.target.files?.[0])}/><b>{slot}</b><span>{clip.file?.name||'Выбрать видео'}</span></button>}
function Range({label,value,min,max,set}:{label:string;value:number;min:number;max:number;set:(n:number)=>void}){return <label className="v2range"><span>{label}<b>{value}</b></span><input type="range" value={value} min={min} max={max} onChange={e=>set(Number(e.target.value))}/></label>}
function Color({label,value,set}:{label:string;value:string;set:(s:string)=>void}){return <label className="v2color">{label}<input type="color" value={value} onChange={e=>set(e.target.value)}/></label>}
